<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.23">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IncidentTracker.Application\IncidentTracker.Application.csproj" />
    <ProjectReference Include="..\IncidentTracker.Infrastructure\IncidentTracker.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewaes\" />
    <Folder Include="Extensions\" />
    <Folder Include="Settings\" />
  </ItemGroup>

	

</Project>
